application: ppeeepp
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: index.py

- url: /privacy
  script: privacy.py
  
- url: /upload.php
  script: upload.py
  
- url: /upload2.php
  script: upload2.py
  
- url: /update.php
  script: update.py
  
- url: /my/?
  script: my.py
  
- url: /([0-9a-f]{8})/?
  script: view.py

# statics
- url: /assets
  static_dir: assets
  
- url: /favicon.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico