application: peeep-us
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  script: index.py
  
- url: /upload.php
  script: upload.py
  
- url: /update.php
  script: update.py
  
- url: /my/?
  script: my.py
  
- url: /([0-9a-f]{8})/?
  script: view.py
  
- url: /pages/(\w+)/?
  script: statics.py

# statics
- url: /assets
  static_dir: assets
  
- url: /favicon.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /.*
  script: e404.py
